=== dannyswat/reportgo/schemas/reportgo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:rg="http://reportgo.io/schema/v1"
           targetNamespace="http://reportgo.io/schema/v1"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">

    <!-- ==================== Root Element ==================== -->
    <xs:element name="report" type="rg:ReportType">
        <xs:annotation>
            <xs:documentation>Root element for ReportGo PDF templates</xs:documentation>
        </xs:annotation>
    </xs:element>

    <!-- ==================== Simple Types ==================== -->
    
    <xs:simpleType name="OrientationType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="portrait"/>
            <xs:enumeration value="landscape"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="UnitType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="mm"/>
            <xs:enumeration value="cm"/>
            <xs:enumeration value="in"/>
            <xs:enumeration value="pt"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="PageFormatType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="A3"/>
            <xs:enumeration value="A4"/>
            <xs:enumeration value="A5"/>
            <xs:enumeration value="Letter"/>
            <xs:enumeration value="Legal"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="FontStyleType">
        <xs:restriction base="xs:string">
            <xs:enumeration value=""/>
            <xs:enumeration value="B"/>
            <xs:enumeration value="I"/>
            <xs:enumeration value="BI"/>
            <xs:enumeration value="U"/>
            <xs:enumeration value="BU"/>
            <xs:enumeration value="IU"/>
            <xs:enumeration value="BIU"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="AlignType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="L"/>
            <xs:enumeration value="C"/>
            <xs:enumeration value="R"/>
            <xs:enumeration value="J"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ColumnFormatType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="string"/>
            <xs:enumeration value="number"/>
            <xs:enumeration value="currency"/>
            <xs:enumeration value="date"/>
            <xs:enumeration value="percent"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ColorValueType">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="255"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="HexColorType">
        <xs:restriction base="xs:string">
            <xs:pattern value="#[0-9A-Fa-f]{6}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="NamedColorType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="black"/>
            <xs:enumeration value="white"/>
            <xs:enumeration value="red"/>
            <xs:enumeration value="green"/>
            <xs:enumeration value="blue"/>
            <xs:enumeration value="gray"/>
            <xs:enumeration value="lightgray"/>
            <xs:enumeration value="darkgray"/>
            <xs:enumeration value="yellow"/>
            <xs:enumeration value="orange"/>
            <xs:enumeration value="purple"/>
            <xs:enumeration value="cyan"/>
            <xs:enumeration value="magenta"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ColorAttributeType">
        <xs:union memberTypes="rg:HexColorType rg:NamedColorType"/>
    </xs:simpleType>

    <xs:simpleType name="TemplateStringType">
        <xs:annotation>
            <xs:documentation>String that may contain Go template expressions like {{.Variable}}</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="PositiveDecimal">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- ==================== Complex Types ==================== -->

    <xs:complexType name="ReportType">
        <xs:sequence>
            <xs:element name="metadata" type="rg:MetadataType" minOccurs="0"/>
            <xs:element name="document" type="rg:DocumentType"/>
            <xs:element name="fonts" type="rg:FontsType" minOccurs="0"/>
            <xs:element name="styles" type="rg:StylesType" minOccurs="0"/>
            <xs:element name="header" type="rg:HeaderFooterType" minOccurs="0"/>
            <xs:element name="footer" type="rg:HeaderFooterType" minOccurs="0"/>
            <xs:element name="sections" type="rg:SectionsType"/>
        </xs:sequence>
        <xs:attribute name="version" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="MetadataType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:element name="author" type="xs:string" minOccurs="0"/>
            <xs:element name="created" type="xs:dateTime" minOccurs="0"/>
            <xs:element name="modified" type="xs:dateTime" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DocumentType">
        <xs:sequence>
            <xs:element name="margins" type="rg:MarginsType" minOccurs="0"/>
            <xs:element name="customSize" type="rg:CustomSizeType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="orientation" type="rg:OrientationType" default="portrait"/>
        <xs:attribute name="unit" type="rg:UnitType" default="mm"/>
        <xs:attribute name="format" type="rg:PageFormatType" default="A4"/>
    </xs:complexType>

    <xs:complexType name="MarginsType">
        <xs:attribute name="top" type="rg:PositiveDecimal" default="15"/>
        <xs:attribute name="right" type="rg:PositiveDecimal" default="15"/>
        <xs:attribute name="bottom" type="rg:PositiveDecimal" default="15"/>
        <xs:attribute name="left" type="rg:PositiveDecimal" default="15"/>
    </xs:complexType>

    <xs:complexType name="CustomSizeType">
        <xs:attribute name="width" type="rg:PositiveDecimal" use="required"/>
        <xs:attribute name="height" type="rg:PositiveDecimal" use="required"/>
    </xs:complexType>

    <xs:complexType name="FontsType">
        <xs:sequence>
            <xs:element name="font" type="rg:FontType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="FontType">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="family" type="xs:string" use="required"/>
        <xs:attribute name="style" type="rg:FontStyleType" default=""/>
        <xs:attribute name="file" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="StylesType">
        <xs:sequence>
            <xs:element name="style" type="rg:StyleType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="StyleType">
        <xs:sequence>
            <xs:element name="fontFamily" type="xs:string" minOccurs="0"/>
            <xs:element name="fontStyle" type="rg:FontStyleType" minOccurs="0"/>
            <xs:element name="fontSize" type="rg:PositiveDecimal" minOccurs="0"/>
            <xs:element name="textColor" type="rg:RGBColorType" minOccurs="0"/>
            <xs:element name="fillColor" type="rg:RGBColorType" minOccurs="0"/>
            <xs:element name="align" type="rg:AlignType" minOccurs="0"/>
            <xs:element name="lineHeight" type="rg:PositiveDecimal" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="extends" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="RGBColorType">
        <xs:attribute name="r" type="rg:ColorValueType" use="required"/>
        <xs:attribute name="g" type="rg:ColorValueType" use="required"/>
        <xs:attribute name="b" type="rg:ColorValueType" use="required"/>
    </xs:complexType>

    <xs:complexType name="HeaderFooterType">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="text" type="rg:TextElementType"/>
                <xs:element name="image" type="rg:ImageElementType"/>
                <xs:element name="line" type="rg:LineElementType"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="enabled" type="xs:boolean" default="true"/>
        <xs:attribute name="height" type="rg:PositiveDecimal" default="15"/>
    </xs:complexType>

    <xs:complexType name="SectionsType">
        <xs:sequence>
            <xs:element name="section" type="rg:SectionType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="SectionType">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="text" type="rg:TextElementType"/>
                <xs:element name="image" type="rg:ImageElementType"/>
                <xs:element name="table" type="rg:TableElementType"/>
                <xs:element name="list" type="rg:ListElementType"/>
                <xs:element name="keyValueList" type="rg:KeyValueListElementType"/>
                <xs:element name="line" type="rg:LineElementType"/>
                <xs:element name="rectangle" type="rg:RectangleElementType"/>
                <xs:element name="row" type="rg:RowElementType"/>
                <xs:element name="spacer" type="rg:SpacerElementType"/>
                <xs:element name="pageBreak" type="rg:PageBreakElementType"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="pageBreakBefore" type="xs:boolean" default="false"/>
        <xs:attribute name="pageBreakAfter" type="xs:boolean" default="false"/>
        <xs:attribute name="condition" type="rg:TemplateStringType"/>
        <xs:attribute name="loop" type="rg:TemplateStringType"/>
        <xs:attribute name="loopVariable" type="xs:string"/>
        <xs:attribute name="paddingLeft" type="rg:PositiveDecimal"/>
    </xs:complexType>

    <!-- ==================== Element Types ==================== -->

    <xs:complexType name="TextElementType" mixed="true">
        <xs:attribute name="style" type="xs:string"/>
        <xs:attribute name="x" type="xs:decimal"/>
        <xs:attribute name="y" type="xs:decimal"/>
        <xs:attribute name="width" type="rg:PositiveDecimal"/>
        <xs:attribute name="align" type="rg:AlignType"/>
        <xs:attribute name="wrap" type="xs:boolean" default="false"/>
        <xs:attribute name="spacingAfter" type="rg:PositiveDecimal"/>
        <xs:attribute name="condition" type="rg:TemplateStringType"/>
    </xs:complexType>

    <xs:complexType name="ImageElementType">
        <xs:attribute name="path" type="rg:TemplateStringType" use="required"/>
        <xs:attribute name="x" type="xs:decimal"/>
        <xs:attribute name="y" type="xs:decimal"/>
        <xs:attribute name="width" type="rg:PositiveDecimal" use="required"/>
        <xs:attribute name="height" type="rg:PositiveDecimal"/>
        <xs:attribute name="align" type="rg:AlignType"/>
        <xs:attribute name="spacingAfter" type="rg:PositiveDecimal"/>
        <xs:attribute name="condition" type="rg:TemplateStringType"/>
    </xs:complexType>

    <xs:complexType name="TableElementType">
        <xs:sequence>
            <xs:element name="alternateRowColor" type="rg:RGBColorType" minOccurs="0"/>
            <xs:element name="columns" type="rg:ColumnsType"/>
        </xs:sequence>
        <xs:attribute name="dataSource" type="rg:TemplateStringType" use="required"/>
        <xs:attribute name="headerStyle" type="xs:string"/>
        <xs:attribute name="cellStyle" type="xs:string"/>
        <xs:attribute name="border" type="xs:boolean" default="true"/>
        <xs:attribute name="spacingAfter" type="rg:PositiveDecimal"/>
        <xs:attribute name="condition" type="rg:TemplateStringType"/>
    </xs:complexType>

    <xs:complexType name="ColumnsType">
        <xs:sequence>
            <xs:element name="column" type="rg:ColumnType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ColumnType">
        <xs:attribute name="header" type="xs:string" use="required"/>
        <xs:attribute name="field" type="xs:string" use="required"/>
        <xs:attribute name="width" type="rg:PositiveDecimal" use="required"/>
        <xs:attribute name="align" type="rg:AlignType" default="L"/>
        <xs:attribute name="format" type="rg:ColumnFormatType" default="string"/>
    </xs:complexType>

    <xs:complexType name="ListElementType">
        <xs:attribute name="items" type="rg:TemplateStringType" use="required"/>
        <xs:attribute name="style" type="xs:string"/>
        <xs:attribute name="bullet" type="xs:string" default="•"/>
        <xs:attribute name="indent" type="rg:PositiveDecimal" default="10"/>
        <xs:attribute name="spacingAfter" type="rg:PositiveDecimal"/>
        <xs:attribute name="condition" type="rg:TemplateStringType"/>
    </xs:complexType>

    <xs:complexType name="KeyValueListElementType">
        <xs:sequence>
            <xs:element name="item" type="rg:KeyValueItemType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="style" type="xs:string"/>
        <xs:attribute name="keyWidth" type="rg:PositiveDecimal" default="50"/>
        <xs:attribute name="spacingAfter" type="rg:PositiveDecimal"/>
        <xs:attribute name="condition" type="rg:TemplateStringType"/>
    </xs:complexType>

    <xs:complexType name="KeyValueItemType">
        <xs:attribute name="key" type="xs:string" use="required"/>
        <xs:attribute name="value" type="rg:TemplateStringType" use="required"/>
    </xs:complexType>

    <xs:complexType name="LineElementType">
        <xs:attribute name="x1" type="xs:decimal" use="required"/>
        <xs:attribute name="y1" type="xs:decimal" use="required"/>
        <xs:attribute name="x2" type="xs:decimal" use="required"/>
        <xs:attribute name="y2" type="xs:decimal" use="required"/>
        <xs:attribute name="color" type="rg:ColorAttributeType" default="black"/>
        <xs:attribute name="width" type="rg:PositiveDecimal" default="0.5"/>
        <xs:attribute name="spacingAfter" type="rg:PositiveDecimal"/>
        <xs:attribute name="condition" type="rg:TemplateStringType"/>
    </xs:complexType>

    <xs:complexType name="RectangleElementType">
        <xs:sequence>
            <xs:element name="fillColor" type="rg:RGBColorType" minOccurs="0"/>
            <xs:element name="borderColor" type="rg:RGBColorType" minOccurs="0"/>
            <xs:element name="borderWidth" type="rg:PositiveDecimal" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="x" type="xs:decimal" use="required"/>
        <xs:attribute name="y" type="xs:decimal" use="required"/>
        <xs:attribute name="width" type="rg:PositiveDecimal" use="required"/>
        <xs:attribute name="height" type="rg:PositiveDecimal" use="required"/>
        <xs:attribute name="radius" type="rg:PositiveDecimal" default="0"/>
        <xs:attribute name="spacingAfter" type="rg:PositiveDecimal"/>
        <xs:attribute name="condition" type="rg:TemplateStringType"/>
    </xs:complexType>

    <xs:complexType name="RowElementType">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="text" type="rg:TextElementType"/>
                <xs:element name="image" type="rg:ImageElementType"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="spacingAfter" type="rg:PositiveDecimal"/>
        <xs:attribute name="condition" type="rg:TemplateStringType"/>
    </xs:complexType>

    <xs:complexType name="SpacerElementType">
        <xs:attribute name="height" type="rg:PositiveDecimal" use="required"/>
        <xs:attribute name="spacingAfter" type="rg:PositiveDecimal"/>
        <xs:attribute name="condition" type="rg:TemplateStringType"/>
    </xs:complexType>

    <xs:complexType name="PageBreakElementType">
        <xs:attribute name="condition" type="rg:TemplateStringType"/>
    </xs:complexType>

</xs:schema>

=== dannyswat/reportgo/templates/examples/payslip.xml
<?xml version="1.0" encoding="UTF-8"?>
<report xmlns="http://reportgo.io/schema/v1"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://reportgo.io/schema/v1 ../../schemas/reportgo.xsd"
        version="1.0">
    
    <metadata>
        <name>Employee Payslip</name>
        <description>Template for employee payslip</description>
        <author>ReportGo</author>
    </metadata>
    
    <document orientation="portrait" unit="mm" format="A4">
        <margins top="15" right="15" bottom="15" left="15"/>
    </document>
    
    <fonts>
        <font name="arialunicode" family="Arial Unicode MS" style="" file="/System/Library/Fonts/Supplemental/Arial Unicode.ttf"/>
    </fonts>
    
    <styles>
        <style name="company_name">
            <fontFamily>Arial Unicode MS</fontFamily>
            <fontSize>16</fontSize>
            <textColor r="0" g="51" b="102"/>
            <align>C</align>
        </style>
        
        <style name="title">
            <fontFamily>Arial Unicode MS</fontFamily>
            <fontSize>12</fontSize>
            <textColor r="0" g="0" b="0"/>
            <align>C</align>
        </style>
        
        <style name="section_header">
            <fontFamily>Arial Unicode MS</fontFamily>
            <fontSize>10</fontSize>
            <textColor r="255" g="255" b="255"/>
            <fillColor r="0" g="51" b="102"/>
            <align>L</align>
        </style>
        
        <style name="label">
            <fontFamily>Arial Unicode MS</fontFamily>
            <fontSize>9</fontSize>
            <textColor r="80" g="80" b="80"/>
            <align>L</align>
        </style>
        
        <style name="value">
            <fontFamily>Arial Unicode MS</fontFamily>
            <fontSize>9</fontSize>
            <textColor r="0" g="0" b="0"/>
            <align>L</align>
        </style>
        
        <style name="table_header">
            <fontFamily>Arial Unicode MS</fontFamily>
            <fontSize>8</fontSize>
            <textColor r="255" g="255" b="255"/>
            <fillColor r="70" g="70" b="70"/>
            <align>C</align>
        </style>
        
        <style name="table_cell">
            <fontFamily>Arial Unicode MS</fontFamily>
            <fontSize>8</fontSize>
            <textColor r="0" g="0" b="0"/>
            <align>L</align>
        </style>
        
        <style name="total_row">
            <fontFamily>Arial Unicode MS</fontFamily>
            <fontSize>9</fontSize>
            <textColor r="0" g="0" b="0"/>
            <align>R</align>
        </style>
        
        <style name="net_pay">
            <fontFamily>Arial Unicode MS</fontFamily>
            <fontSize>11</fontSize>
            <textColor r="0" g="102" b="0"/>
            <align>C</align>
        </style>
        
        <style name="footer_text">
            <fontFamily>Arial Unicode MS</fontFamily>
            <fontSize>8</fontSize>
            <textColor r="128" g="128" b="128"/>
            <align>C</align>
        </style>
    </styles>
    
    <sections>
        <!-- Company Header -->
        <section name="header_section">
            <image path="templates/examples/Acme-corp.png" width="50" height="15" align="C" spacingAfter="2"/>
            <text style="label" align="C" spacingAfter="1">{{.CompanyAddress}}</text>
            <text style="label" align="C" spacingAfter="5">{{.CompanyContact}}</text>
            <line x1="15" y1="0" x2="195" y2="0" width="0.5" color="r:0 g:51 b:102"/>
            <text style="title" spacingAfter="5">PAYSLIP</text>
        </section>
        
        <!-- Pay Period and Employee Info -->
        <section name="info_section">
            <keyValueList style="value" keyWidth="35" valueWidth="55" spacingAfter="1">
                <item key="Pay Period:" value="{{.PayPeriod}}"/>
                <item key="Pay Date:" value="{{.PayDate}}"/>
            </keyValueList>
            <line x1="15" y1="0" x2="195" y2="0" width="0.2" color="r:200 g:200 b:200"/>
            <keyValueList style="value" keyWidth="35" valueWidth="55" spacingAfter="5">
                <item key="Employee ID:" value="{{.EmployeeID}}"/>
                <item key="Name:" value="{{.EmployeeName}}"/>
                <item key="Department:" value="{{.Department}}"/>
                <item key="Position:" value="{{.Position}}"/>
            </keyValueList>
        </section>
        
        <!-- Earnings Section -->
        <section name="earnings_section">
            <text style="section_header" width="180" spacingAfter="1">  EARNINGS</text>
            <table dataSource="{{.Earnings}}" headerStyle="table_header" 
                   cellStyle="table_cell" border="true" spacingAfter="1">
                <columns>
                    <column header="Description" field="description" width="90" align="L"/>
                    <column header="Units" field="units" width="25" align="C"/>
                    <column header="Rate" field="rate" width="30" align="R" format="currency"/>
                    <column header="Amount" field="amount" width="35" align="R" format="currency"/>
                </columns>
            </table>
            <keyValueList style="total_row" keyWidth="145" valueWidth="35" valueAlign="R" spacingAfter="5">
                <item key="Total Earnings:" value="{{.TotalEarnings}}"/>
            </keyValueList>
        </section>
        
        <!-- Deductions Section -->
        <section name="deductions_section">
            <text style="section_header" width="180" spacingAfter="1">  DEDUCTIONS</text>
            <table dataSource="{{.Deductions}}" headerStyle="table_header" 
                   cellStyle="table_cell" border="true" spacingAfter="1">
                <columns>
                    <column header="Description" field="description" width="145" align="L"/>
                    <column header="Amount" field="amount" width="35" align="R" format="currency"/>
                </columns>
            </table>
            <keyValueList style="total_row" keyWidth="145" valueWidth="35" valueAlign="R" spacingAfter="5">
                <item key="Total Deductions:" value="{{.TotalDeductions}}"/>
            </keyValueList>
        </section>
        
        <!-- Net Pay Section -->
        <section name="net_pay_section">
            <rectangle x="15" y="0" width="180" height="10" fillColor="r:240 g:248 b:255" borderColor="r:0 g:51 b:102"/>
            <text style="net_pay" width="180" spacingAfter="8">NET PAY: {{.NetPay}}</text>
        </section>
        
        <!-- Payment Details -->
        <section name="payment_section">
            <text style="section_header" width="180" spacingAfter="1">  PAYMENT DETAILS</text>
            <keyValueList style="value" keyWidth="45" valueWidth="135" spacingAfter="5">
                <item key="Bank:" value="{{.BankName}}"/>
                <item key="Account:" value="{{.AccountNumber}}"/>
                <item key="Payment Method:" value="{{.PaymentMethod}}"/>
            </keyValueList>
        </section>
        
        <!-- Footer -->
        <section name="footer_section">
            <line x1="15" y1="0" x2="195" y2="0" width="0.2" color="r:200 g:200 b:200"/>
            <text style="footer_text" spacingAfter="1">This is a computer-generated document. No signature is required.</text>
            <text style="footer_text">For queries, please contact HR at {{.HREmail}}</text>
        </section>
    </sections>
</report>
