=== dannyswat/reportgo/schemas/reportgo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:rg="http://reportgo.io/schema/v1"
           targetNamespace="http://reportgo.io/schema/v1"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">

    <!-- ==================== Root Element ==================== -->
    <xs:element name="report" type="rg:ReportType">
        <xs:annotation>
            <xs:documentation>Root element for ReportGo PDF templates</xs:documentation>
        </xs:annotation>
    </xs:element>

    <!-- ==================== Simple Types ==================== -->
    
    <xs:simpleType name="OrientationType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="portrait"/>
            <xs:enumeration value="landscape"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="UnitType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="mm"/>
            <xs:enumeration value="cm"/>
            <xs:enumeration value="in"/>
            <xs:enumeration value="pt"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="PageFormatType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="A3"/>
            <xs:enumeration value="A4"/>
            <xs:enumeration value="A5"/>
            <xs:enumeration value="Letter"/>
            <xs:enumeration value="Legal"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="FontStyleType">
        <xs:restriction base="xs:string">
            <xs:enumeration value=""/>
            <xs:enumeration value="B"/>
            <xs:enumeration value="I"/>
            <xs:enumeration value="BI"/>
            <xs:enumeration value="U"/>
            <xs:enumeration value="BU"/>
            <xs:enumeration value="IU"/>
            <xs:enumeration value="BIU"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="AlignType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="L"/>
            <xs:enumeration value="C"/>
            <xs:enumeration value="R"/>
            <xs:enumeration value="J"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ColumnFormatType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="string"/>
            <xs:enumeration value="number"/>
            <xs:enumeration value="currency"/>
            <xs:enumeration value="date"/>
            <xs:enumeration value="percent"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ColorValueType">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="255"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="HexColorType">
        <xs:restriction base="xs:string">
            <xs:pattern value="#[0-9A-Fa-f]{6}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="NamedColorType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="black"/>
            <xs:enumeration value="white"/>
            <xs:enumeration value="red"/>
            <xs:enumeration value="green"/>
            <xs:enumeration value="blue"/>
            <xs:enumeration value="gray"/>
            <xs:enumeration value="lightgray"/>
            <xs:enumeration value="darkgray"/>
            <xs:enumeration value="yellow"/>
            <xs:enumeration value="orange"/>
            <xs:enumeration value="purple"/>
            <xs:enumeration value="cyan"/>
            <xs:enumeration value="magenta"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ColorAttributeType">
        <xs:union memberTypes="rg:HexColorType rg:NamedColorType"/>
    </xs:simpleType>

    <xs:simpleType name="TemplateStringType">
        <xs:annotation>
            <xs:documentation>String that may contain Go template expressions like {{.Variable}}</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="PositiveDecimal">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- ==================== Complex Types ==================== -->

    <xs:complexType name="ReportType">
        <xs:sequence>
            <xs:element name="metadata" type="rg:MetadataType" minOccurs="0"/>
            <xs:element name="document" type="rg:DocumentType"/>
            <xs:element name="fonts" type="rg:FontsType" minOccurs="0"/>
            <xs:element name="styles" type="rg:StylesType" minOccurs="0"/>
            <xs:element name="header" type="rg:HeaderFooterType" minOccurs="0"/>
            <xs:element name="footer" type="rg:HeaderFooterType" minOccurs="0"/>
            <xs:element name="sections" type="rg:SectionsType"/>
        </xs:sequence>
        <xs:attribute name="version" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="MetadataType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:element name="author" type="xs:string" minOccurs="0"/>
            <xs:element name="created" type="xs:dateTime" minOccurs="0"/>
            <xs:element name="modified" type="xs:dateTime" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DocumentType">
        <xs:sequence>
            <xs:element name="margins" type="rg:MarginsType" minOccurs="0"/>
            <xs:element name="customSize" type="rg:CustomSizeType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="orientation" type="rg:OrientationType" default="portrait"/>
        <xs:attribute name="unit" type="rg:UnitType" default="mm"/>
        <xs:attribute name="format" type="rg:PageFormatType" default="A4"/>
    </xs:complexType>

    <xs:complexType name="MarginsType">
        <xs:attribute name="top" type="rg:PositiveDecimal" default="15"/>
        <xs:attribute name="right" type="rg:PositiveDecimal" default="15"/>
        <xs:attribute name="bottom" type="rg:PositiveDecimal" default="15"/>
        <xs:attribute name="left" type="rg:PositiveDecimal" default="15"/>
    </xs:complexType>

    <xs:complexType name="CustomSizeType">
        <xs:attribute name="width" type="rg:PositiveDecimal" use="required"/>
        <xs:attribute name="height" type="rg:PositiveDecimal" use="required"/>
    </xs:complexType>

    <xs:complexType name="FontsType">
        <xs:sequence>
            <xs:element name="font" type="rg:FontType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="FontType">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="family" type="xs:string" use="required"/>
        <xs:attribute name="style" type="rg:FontStyleType" default=""/>
        <xs:attribute name="file" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="StylesType">
        <xs:sequence>
            <xs:element name="style" type="rg:StyleType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="StyleType">
        <xs:sequence>
            <xs:element name="fontFamily" type="xs:string" minOccurs="0"/>
            <xs:element name="fontStyle" type="rg:FontStyleType" minOccurs="0"/>
            <xs:element name="fontSize" type="rg:PositiveDecimal" minOccurs="0"/>
            <xs:element name="textColor" type="rg:RGBColorType" minOccurs="0"/>
            <xs:element name="fillColor" type="rg:RGBColorType" minOccurs="0"/>
            <xs:element name="align" type="rg:AlignType" minOccurs="0"/>
            <xs:element name="lineHeight" type="rg:PositiveDecimal" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="extends" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="RGBColorType">
        <xs:attribute name="r" type="rg:ColorValueType" use="required"/>
        <xs:attribute name="g" type="rg:ColorValueType" use="required"/>
        <xs:attribute name="b" type="rg:ColorValueType" use="required"/>
    </xs:complexType>

    <xs:complexType name="HeaderFooterType">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="text" type="rg:TextElementType"/>
                <xs:element name="image" type="rg:ImageElementType"/>
                <xs:element name="line" type="rg:LineElementType"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="enabled" type="xs:boolean" default="true"/>
        <xs:attribute name="height" type="rg:PositiveDecimal" default="15"/>
    </xs:complexType>

    <xs:complexType name="SectionsType">
        <xs:sequence>
            <xs:element name="section" type="rg:SectionType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="SectionType">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="text" type="rg:TextElementType"/>
                <xs:element name="image" type="rg:ImageElementType"/>
                <xs:element name="table" type="rg:TableElementType"/>
                <xs:element name="list" type="rg:ListElementType"/>
                <xs:element name="keyValueList" type="rg:KeyValueListElementType"/>
                <xs:element name="line" type="rg:LineElementType"/>
                <xs:element name="rectangle" type="rg:RectangleElementType"/>
                <xs:element name="row" type="rg:RowElementType"/>
                <xs:element name="spacer" type="rg:SpacerElementType"/>
                <xs:element name="pageBreak" type="rg:PageBreakElementType"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="pageBreakBefore" type="xs:boolean" default="false"/>
        <xs:attribute name="pageBreakAfter" type="xs:boolean" default="false"/>
        <xs:attribute name="condition" type="rg:TemplateStringType"/>
        <xs:attribute name="loop" type="rg:TemplateStringType"/>
        <xs:attribute name="loopVariable" type="xs:string"/>
        <xs:attribute name="paddingLeft" type="rg:PositiveDecimal"/>
    </xs:complexType>

    <!-- ==================== Element Types ==================== -->

    <xs:complexType name="TextElementType" mixed="true">
        <xs:attribute name="style" type="xs:string"/>
        <xs:attribute name="x" type="xs:decimal"/>
        <xs:attribute name="y" type="xs:decimal"/>
        <xs:attribute name="width" type="rg:PositiveDecimal"/>
        <xs:attribute name="align" type="rg:AlignType"/>
        <xs:attribute name="wrap" type="xs:boolean" default="false"/>
        <xs:attribute name="spacingAfter" type="rg:PositiveDecimal"/>
        <xs:attribute name="condition" type="rg:TemplateStringType"/>
    </xs:complexType>

    <xs:complexType name="ImageElementType">
        <xs:attribute name="path" type="rg:TemplateStringType" use="required"/>
        <xs:attribute name="x" type="xs:decimal"/>
        <xs:attribute name="y" type="xs:decimal"/>
        <xs:attribute name="width" type="rg:PositiveDecimal" use="required"/>
        <xs:attribute name="height" type="rg:PositiveDecimal"/>
        <xs:attribute name="align" type="rg:AlignType"/>
        <xs:attribute name="spacingAfter" type="rg:PositiveDecimal"/>
        <xs:attribute name="condition" type="rg:TemplateStringType"/>
    </xs:complexType>

    <xs:complexType name="TableElementType">
        <xs:sequence>
            <xs:element name="alternateRowColor" type="rg:RGBColorType" minOccurs="0"/>
            <xs:element name="columns" type="rg:ColumnsType"/>
        </xs:sequence>
        <xs:attribute name="dataSource" type="rg:TemplateStringType" use="required"/>
        <xs:attribute name="headerStyle" type="xs:string"/>
        <xs:attribute name="cellStyle" type="xs:string"/>
        <xs:attribute name="border" type="xs:boolean" default="true"/>
        <xs:attribute name="spacingAfter" type="rg:PositiveDecimal"/>
        <xs:attribute name="condition" type="rg:TemplateStringType"/>
    </xs:complexType>

    <xs:complexType name="ColumnsType">
        <xs:sequence>
            <xs:element name="column" type="rg:ColumnType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ColumnType">
        <xs:attribute name="header" type="xs:string" use="required"/>
        <xs:attribute name="field" type="xs:string" use="required"/>
        <xs:attribute name="width" type="rg:PositiveDecimal" use="required"/>
        <xs:attribute name="align" type="rg:AlignType" default="L"/>
        <xs:attribute name="format" type="rg:ColumnFormatType" default="string"/>
    </xs:complexType>

    <xs:complexType name="ListElementType">
        <xs:attribute name="items" type="rg:TemplateStringType" use="required"/>
        <xs:attribute name="style" type="xs:string"/>
        <xs:attribute name="bullet" type="xs:string" default="•"/>
        <xs:attribute name="indent" type="rg:PositiveDecimal" default="10"/>
        <xs:attribute name="spacingAfter" type="rg:PositiveDecimal"/>
        <xs:attribute name="condition" type="rg:TemplateStringType"/>
    </xs:complexType>

    <xs:complexType name="KeyValueListElementType">
        <xs:sequence>
            <xs:element name="item" type="rg:KeyValueItemType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="style" type="xs:string"/>
        <xs:attribute name="keyWidth" type="rg:PositiveDecimal" default="50"/>
        <xs:attribute name="spacingAfter" type="rg:PositiveDecimal"/>
        <xs:attribute name="condition" type="rg:TemplateStringType"/>
    </xs:complexType>

    <xs:complexType name="KeyValueItemType">
        <xs:attribute name="key" type="xs:string" use="required"/>
        <xs:attribute name="value" type="rg:TemplateStringType" use="required"/>
    </xs:complexType>

    <xs:complexType name="LineElementType">
        <xs:attribute name="x1" type="xs:decimal" use="required"/>
        <xs:attribute name="y1" type="xs:decimal" use="required"/>
        <xs:attribute name="x2" type="xs:decimal" use="required"/>
        <xs:attribute name="y2" type="xs:decimal" use="required"/>
        <xs:attribute name="color" type="rg:ColorAttributeType" default="black"/>
        <xs:attribute name="width" type="rg:PositiveDecimal" default="0.5"/>
        <xs:attribute name="spacingAfter" type="rg:PositiveDecimal"/>
        <xs:attribute name="condition" type="rg:TemplateStringType"/>
    </xs:complexType>

    <xs:complexType name="RectangleElementType">
        <xs:sequence>
            <xs:element name="fillColor" type="rg:RGBColorType" minOccurs="0"/>
            <xs:element name="borderColor" type="rg:RGBColorType" minOccurs="0"/>
            <xs:element name="borderWidth" type="rg:PositiveDecimal" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="x" type="xs:decimal" use="required"/>
        <xs:attribute name="y" type="xs:decimal" use="required"/>
        <xs:attribute name="width" type="rg:PositiveDecimal" use="required"/>
        <xs:attribute name="height" type="rg:PositiveDecimal" use="required"/>
        <xs:attribute name="radius" type="rg:PositiveDecimal" default="0"/>
        <xs:attribute name="spacingAfter" type="rg:PositiveDecimal"/>
        <xs:attribute name="condition" type="rg:TemplateStringType"/>
    </xs:complexType>

    <xs:complexType name="RowElementType">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="text" type="rg:TextElementType"/>
                <xs:element name="image" type="rg:ImageElementType"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="spacingAfter" type="rg:PositiveDecimal"/>
        <xs:attribute name="condition" type="rg:TemplateStringType"/>
    </xs:complexType>

    <xs:complexType name="SpacerElementType">
        <xs:attribute name="height" type="rg:PositiveDecimal" use="required"/>
        <xs:attribute name="spacingAfter" type="rg:PositiveDecimal"/>
        <xs:attribute name="condition" type="rg:TemplateStringType"/>
    </xs:complexType>

    <xs:complexType name="PageBreakElementType">
        <xs:attribute name="condition" type="rg:TemplateStringType"/>
    </xs:complexType>

</xs:schema>

=== dannyswat/reportgo/templates/examples/header_footer.xml
<?xml version="1.0" encoding="UTF-8"?>
<report xmlns="http://reportgo.io/schema/v1"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://reportgo.io/schema/v1 ../../schemas/reportgo.xsd"
        version="1.0">

    <metadata>
        <name>Header Footer Example</name>
        <description>Demonstrates header and footer repeating on every page with page numbers</description>
        <author>ReportGo</author>
    </metadata>

    <document orientation="portrait" unit="mm" format="A4">
        <margins top="25" right="15" bottom="20" left="15"/>
    </document>

    <fonts>
        <font name="notosans" family="Noto Sans" style="" file="fonts/Noto_Sans/static/NotoSans-Regular.ttf"/>
        <font name="notosans-bold" family="Noto Sans" style="B" file="fonts/Noto_Sans/static/NotoSans-Bold.ttf"/>
    </fonts>

    <styles>
        <style name="header_text">
            <fontFamily>Noto Sans</fontFamily>
            <fontStyle>B</fontStyle>
            <fontSize>9</fontSize>
            <textColor r="0" g="51" b="102"/>
            <align>L</align>
        </style>
        <style name="header_date">
            <fontFamily>Noto Sans</fontFamily>
            <fontSize>8</fontSize>
            <textColor r="120" g="120" b="120"/>
            <align>R</align>
        </style>
        <style name="footer_text">
            <fontFamily>Noto Sans</fontFamily>
            <fontSize>8</fontSize>
            <textColor r="120" g="120" b="120"/>
            <align>C</align>
        </style>
        <style name="footer_left">
            <fontFamily>Noto Sans</fontFamily>
            <fontSize>8</fontSize>
            <textColor r="120" g="120" b="120"/>
            <align>L</align>
        </style>
        <style name="title">
            <fontFamily>Noto Sans</fontFamily>
            <fontStyle>B</fontStyle>
            <fontSize>22</fontSize>
            <textColor r="0" g="51" b="102"/>
            <align>C</align>
        </style>
        <style name="heading">
            <fontFamily>Noto Sans</fontFamily>
            <fontStyle>B</fontStyle>
            <fontSize>14</fontSize>
            <textColor r="0" g="51" b="102"/>
            <align>L</align>
        </style>
        <style name="body">
            <fontFamily>Noto Sans</fontFamily>
            <fontSize>11</fontSize>
            <textColor r="0" g="0" b="0"/>
            <align>L</align>
            <lineHeight>6</lineHeight>
        </style>
        <style name="table_header">
            <fontFamily>Noto Sans</fontFamily>
            <fontStyle>B</fontStyle>
            <fontSize>10</fontSize>
            <textColor r="255" g="255" b="255"/>
            <fillColor r="0" g="51" b="102"/>
            <align>C</align>
        </style>
        <style name="table_cell">
            <fontFamily>Noto Sans</fontFamily>
            <fontSize>10</fontSize>
            <textColor r="0" g="0" b="0"/>
            <align>L</align>
        </style>
    </styles>

    <header enabled="true" height="15">
        <text style="header_text" x="15" y="8">{{.CompanyName}}</text>
        <text style="header_date" x="-15" y="8">{{.ReportDate}}</text>
        <line x1="15" y1="14" x2="-15" y2="14" color="#003366" width="0.5"/>
    </header>

    <footer enabled="true" height="15">
        <line x1="15" y1="0" x2="-15" y2="0" color="#003366" width="0.3"/>
        <text style="footer_left" x="15" y="4">{{.DocumentRef}}</text>
        <text style="footer_text" x="-15" y="4" align="R">Page {{.PageNumber}} of {{.TotalPages}}</text>
    </footer>

    <sections>
        <section name="title_section">
            <spacer height="10"/>
            <text style="title" spacingAfter="6">{{.ReportTitle}}</text>
            <text style="body" align="C" spacingAfter="15">{{.ReportSubtitle}}</text>
        </section>

        <section name="overview">
            <text style="heading" spacingAfter="5">Overview</text>
            <text style="body" wrap="true" spacingAfter="10">{{.Overview}}</text>
            <keyValueList style="body" spacingAfter="15">
                <item key="Period" value="{{.Period}}"/>
                <item key="Department" value="{{.Department}}"/>
                <item key="Status" value="{{.Status}}"/>
            </keyValueList>
        </section>

        <section name="quarterly_data">
            <text style="heading" spacingAfter="5">Quarterly Results</text>
            <table dataSource="{{.QuarterlyData}}" headerStyle="table_header" cellStyle="table_cell" border="true" spacingAfter="10">
                <alternateRowColor r="240" g="245" b="250"/>
                <columns>
                    <column header="Quarter" field="quarter" width="35" align="C"/>
                    <column header="Revenue" field="revenue" width="40" align="R"/>
                    <column header="Expenses" field="expenses" width="40" align="R"/>
                    <column header="Profit" field="profit" width="40" align="R"/>
                    <column header="Growth" field="growth" width="25" align="C"/>
                </columns>
            </table>
        </section>

        <section name="departments" loop="{{.Departments}}" loopVariable="dept">
            <text style="heading" spacingAfter="4">{{title .dept.Name}}</text>
            <text style="body" wrap="true" spacingAfter="4">{{.dept.Description}}</text>
            <keyValueList style="body" spacingAfter="4">
                <item key="Head Count" value="{{.dept.HeadCount}}"/>
                <item key="Budget" value="{{.dept.Budget}}"/>
                <item key="Utilization" value="{{.dept.Utilization}}"/>
            </keyValueList>
            <list style="body" items="{{.dept.Highlights}}" bullet="•" indent="6" spacingAfter="10"/>
        </section>

        <section name="notes">
            <text style="heading" spacingAfter="5">Notes</text>
            <text style="body" wrap="true" spacingAfter="6">{{.Notes}}</text>
        </section>
    </sections>
</report>

=== dannyswat/reportgo/templates/examples/report.xml
<?xml version="1.0" encoding="UTF-8"?>
<report xmlns="http://reportgo.io/schema/v1"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://reportgo.io/schema/v1 ../../schemas/reportgo.xsd"
        version="1.0">
    
    <metadata>
        <name>Monthly Sales Report</name>
        <description>Template for monthly sales reports</description>
        <author>ReportGo</author>
    </metadata>
    
    <document orientation="portrait" unit="mm" format="A4">
        <margins top="15" right="15" bottom="15" left="15"/>
    </document>
    
    <fonts>
        <font name="notosans" family="Noto Sans" style="" file="fonts/Noto_Sans/static/NotoSans-Regular.ttf"/>
    </fonts>
    
    <styles>
        <style name="title">
            <fontFamily>Noto Sans</fontFamily>
            <fontStyle></fontStyle>
            <fontSize>24</fontSize>
            <textColor r="0" g="51" b="102"/>
            <align>C</align>
        </style>
        
        <style name="heading1">
            <fontFamily>Noto Sans</fontFamily>
            <fontStyle></fontStyle>
            <fontSize>16</fontSize>
            <textColor r="0" g="0" b="0"/>
            <align>L</align>
        </style>
        
        <style name="body">
            <fontFamily>Noto Sans</fontFamily>
            <fontStyle></fontStyle>
            <fontSize>11</fontSize>
            <textColor r="0" g="0" b="0"/>
            <align>L</align>
            <lineHeight>6</lineHeight>
        </style>
        
        <style name="table_header">
            <fontFamily>Noto Sans</fontFamily>
            <fontStyle></fontStyle>
            <fontSize>10</fontSize>
            <textColor r="255" g="255" b="255"/>
            <fillColor r="0" g="51" b="102"/>
            <align>C</align>
        </style>
        
        <style name="table_cell">
            <fontFamily>Noto Sans</fontFamily>
            <fontStyle></fontStyle>
            <fontSize>10</fontSize>
            <textColor r="0" g="0" b="0"/>
            <align>L</align>
        </style>
    </styles>
    
    <sections>
        <section name="title_section">
            <text style="title" spacingAfter="10">{{.ReportTitle}}</text>
            <text style="body" align="C" spacingAfter="20">{{.ReportSubtitle}}</text>
        </section>
        
        <section name="summary_section">
            <text style="heading1" spacingAfter="5">Executive Summary</text>
            <text style="body" spacingAfter="15" wrap="true">{{.Summary}}</text>
            <keyValueList style="body" spacingAfter="20">
                <item key="Total Revenue" value="{{.TotalRevenue}}"/>
                <item key="Total Orders" value="{{.TotalOrders}}"/>
                <item key="Average Order Value" value="{{.AvgOrderValue}}"/>
            </keyValueList>
        </section>
        
        <section name="data_table_section">
            <text style="heading1" spacingAfter="5">Sales Details</text>
            <table dataSource="{{.SalesData}}" headerStyle="table_header" 
                   cellStyle="table_cell" border="true" spacingAfter="20">
                <alternateRowColor r="245" g="245" b="245"/>
                <columns>
                    <column header="Product" field="product" width="60" align="L"/>
                    <column header="Quantity" field="quantity" width="30" align="C"/>
                    <column header="Unit Price" field="unit_price" width="40" align="R" format="currency"/>
                    <column header="Total" field="total" width="40" align="R" format="currency"/>
                </columns>
            </table>
        </section>
        
        <section name="notes_section">
            <text style="heading1" spacingAfter="5">Notes</text>
            <list style="body" items="{{.Notes}}" bullet="•" indent="10" spacingAfter="15"/>
        </section>
    </sections>
</report>
